### ISSUE TITLE
gnutls: libidn2 is not a dep?

### ISSUE THREAD

**Issue by git-bruh** [kiss-community/repo-community#133]
@Vouivre `gnutls` seems to build fine without `libidn2` which doesn't seem to be present in any repo either.

**Comment by Vouivre** [comment]
HHmmm, interesting. I build all my packages in a chroot before I push them in the repo. That's right, it builds fine. I have removed
this dependency. Thanks!

**Comment by Vouivre** [comment]
Sorry, I forgot to adapt the package version. Fixed.
