### ISSUE TITLE
ppp 2.4.9

### ISSUE THREAD

**Issue by Neustradamus** [kiss-community/repo-community#160]
Can you update PPP to 2.4.9?
- https://github.com/kisslinux/community/tree/master/community/ppp

Source:
- https://github.com/ppp-project/ppp

Ping: @onodera-punpun
cc @ArmaanB

Linked to:
- https://github.com/kisslinux/community/issues/1750

**Comment by dilyn-corner** [comment]
`ppp` was dropped here aa5f7d3572a1f02355077d62d20b9648459a0258

One could always ask for it back with a PR :)
