### ISSUE TITLE
age: age-keygen broken

### ISSUE THREAD

**Issue by noocsharp** [kiss-community/repo-community#217]
It links against `/lib64/ld-linux-x86-64.so.2`, which doesn't exist on musl. To fix it, I got rid of the `-buildmode=pie` option, which seems to make it link statically.

**Comment by dilyn-corner** [comment]
@konimex

This is a stupid bug Alpine ran into years ago https://github.com/golang/go/issues/18243 and they dropped the fix for it because "`bash.make` now support the Alpine work around just fine". Which is... Not a solution to the problem?

**Comment by noocsharp** [comment]
And people wonder why C is still used...

**Comment by noocsharp** [comment]
Yeah, I'll just add that line to our `go` package and call it a day.
