### ISSUE TITLE
chromium build fail, yet again! (missing libavcodec.so)

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo-community#236]
[chromium.LOG](https://github.com/kiss-community/repo-community/files/6175818/chromium.LOG)

Error loading shared library libx265.so.192: No such file or directory (needed by /lib/libavcodec.so.58)
Error relocating /lib/libavcodec.so.58: x265_api_get_192: symbol not found

**Comment by kyx0r** [comment]
Ok it makes no sense why that happened I will rebuild ffmpeg and try making chromium again

**Comment by kyx0r** [comment]
Ok, reinstalling ffmpeg fixed the chrome build. @git-bruh any input on what might of happenned? If not then close the issue I guess.

**Comment by kyx0r** [comment]
Maybe result of this ???? https://github.com/kiss-community/repo-main/issues/24

**Comment by git-bruh** [comment]
`x265` was recently updated, my existing chromium broke too but you can just symlink the new x265 lib to the old name and it should work. You rebuilt ffmpeg to link against the new x265 hence it worked.

**Comment by kyx0r** [comment]
Ok, I would you say that this kind of dependency error may be impossible to track down in a package manager in a simple way?

**Comment by kyx0r** [comment]
If we were to make kiss smarter, how would it know that ffpmeg needs to be rebuit also? :/

**Comment by git-bruh** [comment]
I don't think that the package manager should be taking care of this, the release numbers for the packages should be bumped instead, like https://github.com/kiss-community/repo-community/issues/234.

**Comment by dilyn-corner** [comment]
It's more about smart maintainers in this case. I hadn't realized `x265` used library-breaking sonames. 

I bumped the `ffmpeg` relver to resolve this, and I'll have to watch `x265` when it inevitably happens again after *checks notes* fourteen months of inactivity.
