### ISSUE TITLE
kiss update: Wayland??? How???

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo-community#244]
Well certainly that was not there before. Where the hek did wayland dependency come from?
![2021-03-24-091225_1047x728_scrot](https://user-images.githubusercontent.com/33268383/112325326-7d097480-8cab-11eb-8334-f61dab05f5a1.png)

**Comment by dilyn-corner** [comment]
This is the fault of `libva`; the wrong depends/build file were carried over from my own repo. Apologies, fixed in 52edae262d5213cfab07a9928c502428d4be2af4
