### ISSUE TITLE
gnutls: changes required for glib-networking

### ISSUE THREAD

**Issue by git-bruh** [kiss-community/repo-community#261]
@Vouivre Hi, `glib-networking` 2.68.0 seems to require gnutls built with `p11-kit` support (`undefined reference to gnutls_pkcs11_*`), the following changes to the `gnutls` package are required:

* Add `p11-kit` to the `depends` file.
* Remove `--without-p11-kit` from the `build` file.

I tried building `glib-networking` with `libressl` instead of `gnutls`, but it needs `openssl`, `libressl` build errors out with missing stuff from headers.

**Comment by dilyn-corner** [comment]
The only thing mentioned in the NEWS for `glib-networking referring to `p11-kit` is this blurb: 
```
* gnutls
   Added gnutls-pkcs11 backend, which uses gnutls 2.12.8 and
   p11-kit (a new optional dependency) to provide access to
   PKCS#11 tokens. At the moment, this is only enabled if you
   set GIO_USE_TLS=gnutls-pkcs11 in the environment. (Stef,
   #656361)
```
Though that is from version 2.31.2 - if something changed it's a little rude of them to not mention it. Did you do any extensive looking into this? It looks like Void/Alpine have always used `p11-kit` with their `gnutls` so it's hard to tell.

**Comment by Vouivre** [comment]
I'll wait for your confirmation to do the change. If it can wait a few days, I can also have a look at it later.

**Comment by git-bruh** [comment]
Looks like the issue was introduced in [this commit](https://github.com/GNOME/glib-networking/commit/9b3d30e40f306f0e36e2a396d3b6df1edeea9f21#diff-89466e5c89397275f16b9dcba25fdb8ff7b14b1d4fdedd6fa20b8d3656ccf8b6R599) after they re-added `pkcs#11` support. It builds if i do a hack like [this](https://0x0.st/-bDz.patch
) in 2 places where `gnutls_pkcs11_init` and `gnutls_pkcs11_add_provider` are used. I don't think this code is even used anywhere since it's in the `tests` dir and the `sha256sum` of `/usr/lib/gio/modules/libgiognutls.so` (the only thing built) remains the same.

**Comment by git-bruh** [comment]
just stopped the tests from being built

**Comment by dilyn-corner** [comment]
For those curious, you can see that the tests are the only problem when building `gnutls` without `p11-kit`.

**Comment by git-bruh** [comment]
(webkit also warns (since `glib-networking` 2.66.0, and earlier too probably) about the requested gnutls pkcs11 module not being loaded (not found) but that doesn't really matter since the core tls/ssl stuff works fine with `gnutls`, can be suppressed by `export GIO_USE_TLS=gnutls`, i guess the defaults were changed at some points to always try to load the pkcs11 module)
