### ISSUE TITLE
ytfzf: package without all features ?

### ISSUE THREAD

**Issue by Vouivre** [kiss-community/repo-community#268]
Hello,

I use `ytfzf` to watch some videos on youtube. It's available here:

https://github.com/pystardust/ytfzf

Recently I had to install a new version and I noticed now there are some
releases. So even if it's a shell script, it would make sense to create a package. This script can be used with:

- dmenu
- fzf
- ueberzug

`dmenu` and `fzf` are packaged, but `ueberzug` is not packaged. I don't use it and I don't want to package each python module. 
So I could create a package with a comment at the end of the installation. The user should have to install `dmenu`, `fzf` or `ueberzug`. So I could only package `ytfzf`. In this case, it wouldn't be possible to use it directly. It has the advantage that the user can install only what he wants to. If the user only want `dmenu`, he doesn't need to install `ueberzug` and `fzf`.

Another possibily would be to add some dependencies such that `ytfzf` would be usable out of the box. I could add `dmenu`, `fzf` or both as dependencies.

As a user it has the advantage that it get updated when a new version is available. 

What do you think about packaging it @dilyn-corner or other users ? 
And with which dependencies ?

EDIT: link to ytfzf added.

**Comment by git-bruh** [comment]
You should just add a message in `post-install` asking the user to install one of either `dmenu` or `fzf` rather than forcing something in the `depends` file.

**Comment by Vouivre** [comment]
Good idea! Normally I don't use `post-install`, so I didn't think about it. 

It remains `ueberzug` which I don't really want to package. It works fine without it.
Is it a problem if the package doesn't offer all features ? 

As I can see `ueberzug` require multiple python modules. In that case the user could install them with `pip`.

**Comment by git-bruh** [comment]
Yeah they could locally `pip install` it, I don't feel that it's a problem cuz `ueberzug` seems to be needed only for thumbnails. It's good to not pollute repo with `python-*` cruft.

**Comment by Vouivre** [comment]
Fine, thanks! So I'll package it.

**Comment by dilyn-corner** [comment]
`python*` cruft is a fun point that we [get to break new ground on](https://freenode.logbot.info/kisslinux/20200210#c3222008). 

I hate `python-*` and wish there was a *good* way to use `kiss` to abuse `pip`, `npm`, et al. But I trust users to know their $LANG package manager more than I want to fill community up with 600 packages that amount to `pip install yet-another-dependency`. 

A `post-install` message is ideal in these scenarios and is a good solution here :)
