### ISSUE TITLE
Package electron

### ISSUE THREAD

**Issue by jedahan** [kiss-community/repo-community#29]
There are enough useful applications that electron should be packaged.

**Comment by mmatongo** [comment]
If I remember correctly electron depends on `java` and citing from personal experience, the JRE is a whole other type of hell to compile.

**Comment by git-bruh** [comment]
https://github.com/void-linux/void-packages/tree/master/srcpkgs/electron9/files/musl-patches

**Comment by mmatongo** [comment]
I'll try port it over but no promises, it looks really bad.

**Comment by periish** [comment]
For those seeking electron apps, dylan’s kiss-flatpak exists. I’d be willing to fork and maintain, should anyone so desire.

**Comment by ArmaanB** [comment]
@periish That would be great, it could be made a part of kiss-community as well. I know that @jedahan was toying around with flatpaks earlier, so you could build off of that

**Comment by git-bruh** [comment]
From the guidestones:

> The following list of software must never make its way into the repositories as their inclusion will open the floodgates for software which unoptionally depends on them. dbus, systemd, polkit, gettext, intltool, pulseaudio, pipewire, pam, wayland, logind, ConsoleKit, libsn, electron and all DEs.

A separate repo can be made for electron if anyone manages to package it.
