### ISSUE TITLE
libgit2: missing dependency

### ISSUE THREAD

**Issue by git-bruh** [kiss-community/repo-community#300]
@mmatongo `libgit2` seems to be missing a dependency on `cmake`. Also nothing actually builds against`libgit2` (which is only packaged as a static library) due to undefined references symbols provided by `zlib`, `pthread` etc. So `-lz -lpthread -lcrypto -lssl` need to be passed manually (There's nothing in the pkgconfig file either). It works fine without intervention if there's a shared lib available, so maybe that should be enabled aswell.

**Comment by mmatongo** [comment]
I'll fix the dependency.

Dylan mentioned that nothing builds against `libgit2` when I first made the pull for it and the conclusion of that discussion I think was that it was better to have it in the repos and not need it than to need it and not have it.

At the time I was using `stagit` heavily so it benefited me to have it in the community repos so I didn't have to think too much about it should I reinstall kiss or anything.

**Comment by dilyn-corner** [comment]
Closed by #304
