### ISSUE TITLE
surf: white screen bug

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo-community#309]
It's likely a system library bug, but when I go to paypal.com using surf, I get the page loaded for ~2 seconds fine but then it immediately turns white. I have tested my surf build on different kiss rigs and they all have same bug. I have also tested same exact surf version on arch-linux webkit2gtk 2.32.0 version seems to be the same as current but this bug does not happen.

**Comment by HellMederimBoy** [comment]
I had the same problem, I thought it was the webkitgtk compile.

**Comment by kyx0r** [comment]
Did you manage to fix it? How? Recompile webkitgtk? It is a compliler bug?

**Comment by dilyn-corner** [comment]
@git-bruh is this one of those 'known problems and surf is just hopeless here' cases or one of those 'we've probably done something horribly wrong' cases?

**Comment by HellMederimBoy** [comment]
> Did you manage to fix it? How? Recompile webkitgtk? It is a compliler bug? 

I don't fixed i just leave it. Maybe is webkitgtk, compile a yourself webkitgtk maybe solve the problem.

**Comment by kyx0r** [comment]
> @git-bruh is this one of those 'known problems and surf is just hopeless here' cases or one of those 'we've probably done something horribly wrong' cases?

Maybe this patch is broken? https://github.com/kiss-community/repo-community/blob/main/community/webkit2gtk/patches/icu-69.patch

**Comment by git-bruh** [comment]
@dilyn-corner It seems to happen with `lariza` too so I don't think it's a surf bug.

@kyx0r For me this bug only happens on paypal, and also duckduckgo doesn't load (never did for me), just white screens without showing anything, can you confirm ?

**Comment by HellMederimBoy** [comment]
Same for me, duckduckgo not load

**Comment by kyx0r** [comment]
@git-bruh Yes, I confirm duckduckgo.com doesn't load. Which is ... actually I remember now this bug dates back 5 month's or more ago, and probably was the reason why I changed my search engine to the lite version. See this commit in my custom build: https://github.com/kyx0r/klec/commit/7748179bb94860ec7241f6e88e8ac127186ef525#diff-0199311728be829918c18b5f1486d315ba690ed58b69b4c8236a16416130bcd2

**Comment by git-bruh** [comment]
Fixed it, on glibc atleast by switching from `MinSizeRel` to `Release`. Will experiment with musl now, maybe our musl patch is incomplete cuz i see a lot more stuff in [void's patch](https://github.com/void-linux/void-packages/blob/master/srcpkgs/webkit2gtk/patches/fix-musl-javascriptcore.patch).

**Comment by git-bruh** [comment]
Paypal should work now with the PR, but duckduckgo still doesn't wanna work on musl, even after defining `__WORDSIZE` (used for some hacks) that the compiler was warning about..

**Comment by kyx0r** [comment]
Thank you git bro and everyone else. I really appreciate it man. I hope the issue can be solved completely eventually.

**Comment by git-bruh** [comment]
No problem, sites like duckduckgo should also be working now, updated the PR.
