### ISSUE TITLE
Unable to build gnutls

### ISSUE THREAD

**Issue by ilmich** [kiss-community/repo-community#320]
Hi all,

I'm considering using kiss linux as my main system and I'm doing some testing by compiling the packages I need.
But I'm having trouble compiling gnutls (openconnet is not compatible with libressl).
I can't find the pkg-config package which seems to be needed for dependencies finding.

Where am I wrong !?
Cheers
Michele

**Comment by sdsddsd1** [comment]
You have to ping the maintainer of the package that they can do something about this. `kiss-maintainer gnutls` This should be @cedric@vouivre.org .
Also please submit the build log which can be at the end of the failed build.

**Comment by ilmich** [comment]
Sorry, my fault, the package on kiss linux is named pkgconf .
After installing it the problem was solved.

I'll close the issue
Cheers
Michele

**Comment by sdsddsd1** [comment]
This is at least a missing dependency of `pkgconf make` :)  for the package.

**Comment by Vouivre** [comment]
I'll check it, thanks for the report! :+1:
