### ISSUE TITLE
flashrom: build fail

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo-community#326]
I may need this in some time; to get a custom bios rom into one of my computers. Build does not work on my end. 
[flashrom-2021-04-23-10:37-10385.LOG](https://github.com/kiss-community/repo-community/files/6366088/flashrom-2021-04-23-10.37-10385.LOG)

@ioraff

**Comment by ioraff** [comment]
I'm no longer maintaining this @dilyn-corner

**Comment by dilyn-corner** [comment]
Builds fine for me (after disabling Werror, `clang` must be more strict than `gcc` here...).

Your problem is probably with this line: 
`Checking for libpci headers... Checking for FTDI support... not found.`

Are you sure `pciutils` is installed?

**Comment by kyx0r** [comment]
![2021-04-23-112155_408x104_scrot](https://user-images.githubusercontent.com/33268383/115893445-b6b6d200-a447-11eb-8be7-5c3923904230.png)

Yes I do.

**Comment by kyx0r** [comment]
@dilyn-corner @ioraff Ok, never mind guys. Sorry for bother it works. I just had to reinstall pciutils for some reason. Well happens sometimes...

**Comment by dilyn-corner** [comment]
Strange. If this happens again (specifically for this package but in general for any package), seeing `kiss-manifest pciutils` would be nice, as well as the output of something like `pkg-config --libs libpci`. 
Additionally, `flashrom` runs a test for `libpci` in the usual way; seeing the output of `$(BUILD_DETAILS_FILE)` in the failed build would identify what exactly went wrong, as it doesn't use `pkgconf` for the check - it compiles a test program and `tee`s the output to this.

**Comment by kyx0r** [comment]
@dilyn-corner There may be one thing that is special about the computers I run, I have a script which makes the whole system run in tmpfs with no hard drive. See here: https://github.com/kyx0r/klec/blob/master/shell/migr . This way I don't have to invest in extra hardware. But there is one caveat to this that techically tmpfs is not a real filesystem, it's a swap and it has no real block device backing it also. So I've noticed that after rootfs migration like that some files loose the chattr attributes, not sure if this has effect or not. But I still have the system previous state stored on real harddrive so I can inspect this problem again.

**Comment by kyx0r** [comment]
@dilyn-corner 
Here is what output of kiss-manifest pciutils looked like: 
[manifest_afterreinstall.LOG](https://github.com/kiss-community/repo-community/files/6366645/manifest_afterreinstall.LOG)
[manifest_prev.LOG](https://github.com/kiss-community/repo-community/files/6366646/manifest_prev.LOG)

**Comment by kyx0r** [comment]
And running ```pkg-config --libs libpci```
gives

/ pkg-config --libs libpci
Package libpci was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpci.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libpci', required by 'virtual:world', not found

after reinstall it prints
-lpci

**Comment by kyx0r** [comment]
It maybe it was messed up because a few month's ago I was building chromium build, which had build problems, see the issue here https://github.com/kiss-community/repo-community/issues/53

**Comment by dilyn-corner** [comment]
What a very neat system idea! I love it. 

Looks like the former version you had didn't actually have the pkgconf file or the headers - very hard to build things when that happens. Not sure why that would happen (though I have a few ideas). You could try to run `kiss` how it is mentioned [here](https://freenode.logbot.info/kisslinux/20210412#c7605896) to see if `kiss` is fumbling this somehow. 

This could probably be related to your `chromium` issues as well. Figuring out what's up would basically just take a lot of debugging, log checking, and reproducing on your part. Keep letting me know if you hit these types of walls!

**Comment by kyx0r** [comment]
[flashrom.LOG](https://github.com/kiss-community/repo-community/files/6367251/flashrom.LOG)

Here is the output of ```sh -x $(which kiss) b flashrom >file 2>&1``` 
Not sure if you can make out anything useful out of it, but I might as well run all my updates and installs though this in the future just in case. @dilyn-corner
