### ISSUE TITLE
[Reguest] Add Tor Browser to repo

### ISSUE THREAD

**Issue by hovercats** [kiss-community/repo-community#35]
Id like to request adding Tor browser into the community repo.
To my knowledge, we got a couple of solutions here that we can choose between. 

- We could choose the most obvious reason for this distro, to fetch the source code from their git, and compile it ourself.
- We could fetch the .Tar.xz from torproject.org, and either unpack, and compile, or add it to the community bin repo, but tbh, I see no reason to do just this, seeing as KISS is a sourcebased distro. that is, unless people want it this way for some reason.
- Third and final choice, is to compile Micha Flee's [Torbrowser-launcher](https://github.com/micahflee/torbrowser-launcher)  instead, and let the launcher do the rest. 
 TorBrowser-launcher brings some features to the table, which is listed at his github, but Ill list them here aswell.

 -   Downloads and installs the most recent version of Tor Browser in your language and for your computer's architecture,
      or launches Tor Browser if it's already installed (Tor Browser will automatically update itself)
 -  Verifies Tor Browser's signature for you, to ensure the version you downloaded was cryptographically signed by Tor
      developers and was not tampered with
 - Adds "Tor Browser" and "Tor Browser Launcher Settings" application launcher to your desktop environment's menu
      Includes AppArmor profiles to make a Tor Browser compromise not as bad
 - Optionally plays a modem sound when you open Tor Browser (because Tor is so slow)

Using TorBrowser-launcher, seems to be the prefered method for alot (if not most, or all?) of distros, so from that standpoint, the launcher would be the prefered method. however, using the launcher, adds another package in your filesystem, aswell as its dependencies. on top of TorBrowsers already required dependencies, which probably isnt what we want.

**Comment by git-bruh** [comment]
`torbrowser-launcher` probably won't work as there's no binary available for musl (afaik)

Using this source https://archive.torproject.org/tor-package-archive/torbrowser/10.0.7/src-firefox-tor-browser-78.6.0esr-10.0-1-build1.tar.xz
KISS's firefox-esr no-dbus patch applies, rust 1.48 patch applies, no-gtk2 patch is failing but i can try fixing it and then try building. But i am not sure if we want to patch tor browser like that ? @hovercats

**Comment by hovercats** [comment]
@git-bruh I didnt thought of that tbh. I checked alpine's repos aswell, and they dont have one either. They got Tor, but so do we, but not the browser part. 

Patching it *could* potentially hurt torbrowser, however, that depends entierly on the fact if those dependencies have any real effects on Tor's ability to function as intended. I cant answer that question, as I simply dont know, as its abit out of my scope of knowledge.
In any case, lll do some digging, and see if I can dig up anything about torbrowser on musl libc, aswell as patching it, and then report back with my findings.

If youd be willing to try to fix the gtk2 patch, that would be nice. If all else fails, I can always run it in a chroot-jail, use nix or in a vm or something.

**Comment by git-bruh** [comment]
i "fixed" the no-gtk2 patch (there were some differences in normal firefox and tor's old-configure)

however, only old-configure.in is present in the tor release tarball and not the generated old-configure, it is generated during mach configure here, but im not sure how we can patch it without making the configure script fail first, don't know much about the build system

so if you want to build it currently, you

first, run ./mach configure with all the options,
let it fail,
then apply all the patches

havent tested the build but it configures fine

I'd honestly just use an arch/artix chroot or something

**Comment by hovercats** [comment]
I get the error of missing 'old config' when applying gtk2 patch, retrying ./mach configure will then for me, end in an error of missing 'libpulse'. 

I also tried to do a search on tor on musl libc, and tbh, I have yet to find anything in particular. Im also starting to belive theres a reason for torbrowser not being available on musl libc distros

Im leaning more and more onto rather using a chroot or vm.

**Comment by git-bruh** [comment]
no gtk 2 patch http://ix.io/2Lo9

build yasm and autoconf2.13 as in the firefox build script

```
./mach configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --enable-official-branding \
    --enable-optimize="$CFLAGS -w" \
    --enable-install-strip \
    --enable-strip \
    --enable-rust-simd \
    --enable-application=browser \
    --enable-release \
    --enable-alsa \
    --without-system-nspr \
    --without-system-nss \
    --with-system-jpeg \
    --with-system-zlib \
    --with-system-png \
    --without-system-libvpx \
    --with-system-pixman \
    --with-system-ffi \
    --disable-profiling \
    --disable-accessibility \
    --disable-tests \
    --disable-system-extension-dirs \
    --disable-parental-controls \
    --disable-debug-symbols \
    --disable-callgrind \
    --disable-vtune \
    --disable-elf-hack \
    --disable-gold \
    --disable-jemalloc \
    --disable-pulseaudio \
    --disable-crashreporter \
    --disable-updater \
    --disable-dbus \
    --disable-eme \
    --disable-necko-wifi
```

let it fail
then apply the no-gtk2,dbus,rust patch 

tor  browser should work with musl as it's just a modified version of firefox esr, but im not sure

also the configure options will have to be changed a little for tor-specific things

**Comment by hovercats** [comment]
Running the afforementioned command, willl result in the following error;
`ERROR: Don't know how to translate x86_64-unknown-linux-gnulibc1 for rustc`

This stops the process, and Im unable to continue. This is also way beyond my knowledge.
Unless someone else has the urge to see if they cant fix this, Ill be closing this issue in the next few days.

**Comment by hovercats** [comment]
Ill close this, seeing as Im none the wiser on how to make Tor run on kiss linux. if however you should come up with a solution, feel free to reopen. 

If youve come across this issue hoping to find a solution, Ive come up with none for musl libc, however, there are alternatives to bypass this issue;
Use [GKiss](https://github.com/gkisslinux/grepo#gkiss-linux-) (kiss with glibc instead  of musl libc)
Using [Nix package manager](https://github.com/NixOS/nix)
Using a VM,
or using a chroot enviroment.
