### ISSUE TITLE
qt5-webengine: incomplete package

### ISSUE THREAD

**Issue by sdsddsd1** [kiss-community/repo-community#368]
@dilyn-corner : Have a look at qt5-webengine. There is a lonely patch floating around. (incomplete commit)

**Comment by sdsddsd1** [comment]
This one: https://github.com/kiss-community/repo-community/blob/main/community/qt5-webengine/dbus-patch.patch

**Comment by dilyn-corner** [comment]
oh my goodness. 
4569f797356cc598528caf62def401fa1a894fe3
