### ISSUE TITLE
Neovim build fails with "ninja: subcommand failed"

### ISSUE THREAD

**Issue by AndreiSva** [kiss-community/repo-community#401]
I'm trying to build neovim on kiss running the `kiss build neovim` command. Unfortunately this always results in an error message: "ninja: subcommand failed". Unfortunately i can't offer a text error message because my curent KISS install is in a virtual machine. Here is a screenshot of the error.

![image](https://user-images.githubusercontent.com/51296839/118922956-b5b27c80-b8ef-11eb-8e46-6f8b49dce8d0.png)

I think it might be something to do with either a missing dependency or some outdated package as I was not able to find much information on the internet about this issue.

I would really appreciate if more people could investigate this issue as neovim is a pretty popular text editor :)

**Comment by dilyn-corner** [comment]
I made an issue about this here https://github.com/neovim/neovim/issues/14362 but they haven't done anything about this yet...

I'll probably just change the source.

**Comment by dilyn-corner** [comment]
Changed the source, you should be good to go now. 
We'll change back once they've *finally* released a new version :)
