### ISSUE TITLE
Chromium build fail

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo-community#53]
Hello, this failed with pci/pci.h header missing, I have checked and I only have /linux/pci.h from the kernel-headers but this is not it, otherwise it should have been #include <linux/pci.h> . I am not sure even why this is being compiled in the first place, it looks like some bullshit wrapper code for generating some gpu vulkan crap on android. 
I am attachingrelevant part of the build log:
https://pastebin.com/td0K59a1

Regards,

**Comment by git-bruh** [comment]
https://github.com/kisslinux/community/issues/1637

Just do `kiss fork pciutils` and modify the build file to change `install-pcilib` to `install-lib`

**Comment by git-bruh** [comment]
Also, there's been a new chromium release so you should probably build that instead of this old one. Here: https://github.com/git-bruh/community/tree/chromium/community/chromium, but i haven't tested it on musl yet, build should finish in a few hours.

**Comment by kyx0r** [comment]
@git-bruh Thanks for the quick responce. I have tried building the new release as you said but still got the same error.Then I tried to just install pciutils, got the same error. Then I manually installed pciutils with libs and headers and the build worked. That said, don't you think that pciutils should be made a dependency for chromium and maybe split the change to build script to install the libs? 
But then after a succesfull build I get this stacktrace when running chromium:

[15408:15419:0121/221618.562321:FATAL:udev_loader.cc(38)] Check failed: false.
Received signal 6
  r8: 0000000000000001  r9: 0000000000003c3b r10: 0000000000000008 r11: 0000000000000246
 r12: 00007f18bcd2c9f0 r13: 00007f18bc3faa00 r14: 00007f18bc3fa9c0 r15: 00007f18bc3faf20
  di: 0000000000000002  si: 00007f18bc3fa780  bp: 00007f18bc3fa780  bx: 0000000000000000
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f18c68deb77  sp: 00007f18bc3fa778
  ip: 00007f18c68deb77 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

Any ideas?

**Comment by kyx0r** [comment]
Luckly I have 12 core last gen ryzen 5 PRO 4650 cpu, with 32 gb of overclocked ram, so I can test compile this bloated software somewhat with a grace, it takes about 2 hours to compile this stupid browser even on my high end system with literally every package+kernel compiled with -O3 -march=native -mtune=native. I imagine the horrors of anybody else doing this on a lower spec system and their thing failing midway or whatever. Very frustrating indeed.

**Comment by kyx0r** [comment]
I just finished building the 87. version and it still has the same stacktrace error. Possibly some uvdev library version is wrong? But that cant's be because I have all my packages up to date with the other fork from dylan which is ~120 commits ahead.

**Comment by git-bruh** [comment]
I was getting the same error when running in a chroot. installing `eudev` fixed it and i made it a dependency

**Comment by git-bruh** [comment]
It should definitely work after installing `eudev`:

![2021-01-22-105754_956x1052_scrot](https://user-images.githubusercontent.com/67585967/105450870-6e99df00-5ca1-11eb-9a73-bdfb77f02168.png)

**Comment by kyx0r** [comment]
Thanks for the help! I managed to solve my issue, somehow they were related to eudev conflicts that came out of nowhere. I don't really get why this conflict existed, (maybe something from previous version?) but I just did ```kiss a uedev (conflict name here) ``` and it magically started to work. Here's the screen:

<a href="https://ibb.co/BzmJYCq"><img src="https://i.ibb.co/w0Tq2zM/2021-01-22-180701-719x306-scrot.png" alt="2021-01-22-180701-719x306-scrot" border="0"></a>

**Comment by git-bruh** [comment]
@kyx0r Great! the conflicts might be present if you had `libudev-zero` installed

**Comment by illiliti** [comment]
@git-bruh Another option to avoid udev related issues is building chromium without libudev support (use_udev=false GN flag). Can you please test this ?

**Comment by git-bruh** [comment]
@illiliti Thanks! Rebuilt and seems to work fine now without linking udev

**Comment by git-bruh** [comment]
@illiliti update: for some reason if chromium is not linked to `eudev`, the chromium process doesn't get killed even after closing all tabs with `Ctrl + W`, so if you "close" chromium then try to launch it again, it wont work cuz chromium is already running:
![2021-01-25-131226_1532x88_scrot](https://user-images.githubusercontent.com/67585967/105679328-49f96d80-5f14-11eb-82c8-967eb220717c.png)

This can be reproduced reliably by just launching chromium from the terminal ,opening 1-2 tabs and then closing all of them and observing that the process will just stay stuck and won't exit, so for now i have removed the `use_udev=false` flag
