### ISSUE TITLE
Packages with cmake

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo-community#69]
Hello I've recently made some development libraries for vulkan.
https://github.com/kyx0r/repo-vulkan.git

My question is how do you go about working with cmake, because while they do build and install successfully there is no way to remove then from the system. kiss r package does not actually remove the files installed by cmake (or rather make install). What do I need to change in the build to make it aware of the files?

**Comment by git-bruh** [comment]
You're just doing `make install` instead of `make DESTDIR="$1" install`, which just installs the package into your system's `/usr` directly without actually creating a KISS package

also the preferred format for cmake stuff is

```
export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr
    -Dsomething=OFF

cmake --build build
cmake --install build
```

**Comment by git-bruh** [comment]
and "$1" is the directory where the package files will be installed, and the KISS package is created from that directory only

**Comment by kyx0r** [comment]
Thank you. My packages are fixed now. If you ever want to add them to this repo, feel free to copy from my repo. I will be maintaining those myself because I use them for my work. And I also don't want to be bothered of not having direct push access, making pull requests and all that nonsense. Also, I will at some point package the rest of the vulkan tools so expect that repo to grow, right now it's at the bare minimum on what's needed if you ever decide to write your own game engine using vulkan-api.
