### ISSUE TITLE
Set tcc source to mob branch

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo-community#73]
Hello the version that is downloaded for tcc is like 3 years old. I suggest to download the sources directly from the mob branch which is what people use for production nowadays. 
https://repo.or.cz/w/tinycc.git

This is a special case because over the years numerous bugs we fixed and since this is a compiler, it has no excuses to have bugs if you are building anything meaningful with it. This project has gone into mob state long time ago and nobody knows if the maintainer (grischka) will ever do any releases. But he is very much active. So even if the mob comes to disarray state most of the problems get fixed very quickly. But somehow we still get people now and then reporting bugs that are past decade long on the mailing list because of using the old version. 

--

**Comment by kyx0r** [comment]
Also, since this is a source based distro, that should give it even more incentive to pull the latest version.

**Comment by kyx0r** [comment]
For more about what is mob read here: https://repo.or.cz/h/mob.html

**Comment by sdsddsd1** [comment]
To reach the maintainer of the package you have to ping them. 
@ $(kiss-maintainer tcc)

**Comment by kyx0r** [comment]
I don't know their github username, I'll send him an email. But if not I guess @git-bruh is the curator here while dylan is gone? Or you mean something else by that @ $(kiss-maintainer tcc)? Kiss maintainer only gives me his email.

**Comment by git-bruh** [comment]
@IslandAlpha is the maintainer

```
testuser@KISS tcc 3$ kiss maint tcc
=> /home/testuser/kiss/community/community/tcc
Kris Heck <Kris.Heck@protonmail.com>
```

**Comment by kyx0r** [comment]
@git-bruh And if he never responds? Should I do it myself? It's really not that hard to update the checksum and pick some git commit hash base off of.

**Comment by git-bruh** [comment]
@kyx0r yeah you can do it yourself and send a PR if the maintainer doesn't respond

**Comment by IslandAlpha** [comment]
@kyx0r I've been away from KISS linux for a while now, do you want to take over tcc maintainership?
