### ISSUE TITLE
e2fsprogs: fails to build

### ISSUE THREAD

**Issue by noocsharp** [kiss-community/repo-community#84]
It appears to require `qsort_r` which is missing from musl, although musl does have `qsort`.

See: https://github.com/tytso/e2fsprogs/issues/58

**Comment by git-bruh** [comment]
Thanks for reporting, I mainly run GKISS as host and only rebuild `core`/fat packages or packages which have had previous issues with musl on my musl KISS chroot, will build everything on musl too now.

https://github.com/CarbsLinux/repository/commit/80b426c236a6ffb74f813b7ef8f55eb28ddd203a
