### ISSUE TITLE
msmtp: use libtls instead of gnutls

### ISSUE THREAD

**Issue by noocsharp** [kiss-community/repo-community#91]
msmtp now has up-to-date support for libtls, and once packages are dropped (#89), it will be the only package dependent on gnutls. So I think it makes sense to switch to libtls from gnutls to avoid the dependency.

@Vouivre

**Comment by Vouivre** [comment]
Right, it's on my list. Thanks!

**Comment by Vouivre** [comment]
Done with commit https://github.com/kiss-community/repo-community/commit/1228f5b79735b1bb0ffbea73b001437e74d3d4e3 .
By the way I saw that `pkgconf` was missing as a dependency. 

Now I will probably drop gnutls.
