### ISSUE TITLE
Still necessary to push PR on kisslinux/community ? 

### ISSUE THREAD

**Issue by Vouivre** [kiss-community/repo-community#96]
I will update some of my packages on repo-community, but is it still necessary to push PR on kisslinux/community ? Repology.org now points to repo-community, perhaps it's time to replace kisslinux/community with kiss-community/repo-community. You probably had a discussion about this. We will drop one of those repos pretty soon or later. What are your opinons on this ?

**Comment by git-bruh** [comment]
Yeah i think we should stop sending PRs to `kisslinux/community`, cuz when/if dylan comes back, I doubt he's gonna go through 80+ PRs at once. We'll just merge `repo-community` to `kisslinux/community` at that time.

**Comment by Vouivre** [comment]
It's also what I think. Unless every maintainer know it, I would inform them. I'm not sure an issue on kisslinux/community is the best. Perhaps that information should be posted on reddit. It's interesting for the maintainers and also for the users. And we should also think to the new users that will come. But as far as I know you already had a discussion on this. Perhaps I'm the only one who is not on irc ;-).

**Comment by git-bruh** [comment]
This topic in particular has not been discussed in IRC. It would be a good idea to post it on the subreddit.

**Comment by Vouivre** [comment]
In this case I think it's better that you post it, or somebody who knows what was discussed. Thank you for your answer :+1:!

**Comment by git-bruh** [comment]
I don't have a reddit account, just browse the sub without one. I guess we can make yet another issue on kisslinux/community regarding this?

**Comment by Vouivre** [comment]
It's also a solution. So for the moment we could open an issue on kisslinux/community. I assume a lot, if not all maintainers, will see it.

But later I think we should make more visible how Kiss is evolving. As a new user it can happen I won't search on issues on github. I would have a look at the Kiss website where there are no information about kiss-community.

**Comment by ArmaanB** [comment]
If we get the domain on Feb 14, then this will be much easier. If not, the plan is March 30 we send out a poll / major notice about the future of KISS

**Comment by Vouivre** [comment]
I didn't know. Thanks! I let you open an issue on kisslinux/community ? If yes, I let you close this issue.

**Comment by ArmaanB** [comment]
I will when the time comes, thanks!
