### ISSUE TITLE
Outdated packages

### ISSUE THREAD

**Issue by git-bruh** [kiss-community/repo-community#97]
@xuxiaodong
- [ ] restic: 0.11.0

@xuxiaodong
- [ ] tig: 2.5.1

@mmatongo
- [ ] github-cli: 1.5.0

@dilyn-corner
- [ ] nss: 3.61

@djt3
- [ ] nfs-utils: 2.5.2

**Comment by git-bruh** [comment]
I can take over `btrfs-progs`, `procps-ng`, `imagemagick`, `fuse`, `iputils`

**Comment by Ominitay** [comment]
I am still happy to maintain`i3[-gaps]`, I'll be updating them this weekend.

**Comment by dilyn-corner** [comment]
`ecm` will be bumped when it's no longer an rc (tomorrow).

**Comment by mmatongo** [comment]
I've updated 2 out of 3, I'll work on `tor` tomorrow.

**Comment by git-bruh** [comment]
@Vouivre @mmatongo @noocsharp Would you be willing to adopt a few packages from the orphaned list?

**Comment by mmatongo** [comment]
I'm fine with it.

**Comment by noocsharp** [comment]
I would adopt some if I used any of them, but I don't. Probably best to drop if no one takes them.

**Comment by mmatongo** [comment]
I'll take `lvm2` and `openvpn`

**Comment by git-bruh** [comment]
@mmatongo Could you take over `pkcs11-helper` aswell? It's a dependency for `openvpn`

I'll take over `libisoburn`, `libisofs`, `xwallpaper`.

`syncthing`, `libsndfile`, `libsamplerate`, `fldigi` will have to be dropped.

**Comment by Ominitay** [comment]
i3[-gaps] have been bumped in #103

**Comment by Vouivre** [comment]
I'm in the same case as noocsharp. I don't use any of them. By name I know `syncthing`, but that's all. That's the reason why I dropped `emacs`: I still think it's good to have it in a distribution, but I don't use it anymore. 
But I'm still open to adopt some of them. If some of them are important to have, just tell me which one and I could adopt them.

**Comment by git-bruh** [comment]
@Vouivre It would be nice if you could take `syncthing`, ill drop the 3 remaining packages.

**Comment by Vouivre** [comment]
Ok, I'll take it.

**Comment by git-bruh** [comment]
@Vouivre Yeah I think it would be good to have `emacs` in community since it's pretty popular. You can take back build files from kiss-graveyard

**Comment by Vouivre** [comment]
I also still have it locally. Ok, I bring it back.

**Comment by git-bruh** [comment]
@Vouivre you forgot to re-add `gnutls`

**Comment by Vouivre** [comment]
Sorry, I didn't check, I simply brought `emacs` back to the repo.

**Comment by aaronNGi** [comment]
`socat-1.7.4.1` is [here](https://github.com/kisslinux/community/pull/1743).

I think we should give up on submitting PRs to the original repo.

**Comment by git-bruh** [comment]
@aaronNGi Sorry i was running the outdated script on another branch which didn't have your PR merged. and yeah we should shift completely to this repo from kisslinux/community now.

**Comment by aaronNGi** [comment]
All good.

Okey great, means I can cleanup my repos :)

**Comment by mmatongo** [comment]
Tor is gonna be a min

**Comment by Xeno-Hypster** [comment]
I see that mpd still hasn't been updated, according to this, I'd be happy to take over that if no-one has it.

**Comment by git-bruh** [comment]
@Xeno-Hypster There's an update to 0.22.6, you can send a PR if you use the package. It was orphaned but i just bumped it because it's probably a useful package.

**Comment by Xeno-Hypster** [comment]
Will do then, I do enjoy having my music.

**Comment by git-bruh** [comment]
@dilyn-corner will be handling such issues, since they're the BDFL now.
